restore old version

diff --git a/.github/workflows/digital-ocean-deploy.yml b/.github/workflows/digital-ocean-deploy.yml
--- a/.github/workflows/digital-ocean-deploy.yml
+++ b/.github/workflows/digital-ocean-deploy.yml
@@ -4,65 +4,145 @@ on:
   workflow_call:
     inputs:
       image_name:
+        description: "Image Name"
         required: true
         type: string
+
       docker_container_name:
+        description: "Docker container Name"
         required: true
         type: string
+
       do_host:
+        description: "Digital Ocean host"
         required: true
         type: string
+
       do_username:
+        description: "Digital Ocean username"
         required: true
         type: string
+
       docker_port_mapping:
+        description: "Docker port mapping"
         required: false
         type: number
+
     secrets:
       do_ssh_key:
+        description: "Docker Hub token"
         required: true
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   digital-ocean-deploy:
     runs-on: ubuntu-latest
-    timeout-minutes: 10
+    if: ${{ github.ref_name }}
 
     steps:
-      - name: Deploy via SSH
+      - name: Checkout files
+        uses: actions/checkout@v2
+      - name: Deploy to Digital Ocean droplet via SSH action
         uses: appleboy/ssh-action@v1.0.3
+
         with:
           host: ${{ inputs.do_host }}
           username: ${{ inputs.do_username }}
           key: ${{ secrets.do_ssh_key }}
+
           script: |
-            IMAGE="${{ inputs.image_name }}"
-            NEW_CONTAINER="${{ inputs.docker_container_name }}-new"
-            OLD_CONTAINER="${{ inputs.docker_container_name }}"
 
-            echo "Pull image"
-            docker pull $IMAGE
-
-            echo "Start new container"
-            docker run -d \
-              --name $NEW_CONTAINER \
-              -p $(if [ "${{ inputs.docker_port_mapping }}" ]; then echo ${{ inputs.docker_port_mapping }}; else echo 8000; fi):8000 \
+            # Stop running container
+            docker container stop $(echo ${{ inputs.docker_container_name  }})
+            # Remove old container
+            docker container rm -f $(echo ${{ inputs.docker_container_name  }})
+            # Remove old images
+            docker images -a | grep "$(echo ${{ inputs.docker_container_name }})" | awk '{print $1":"$2}' | xargs docker rmi
+            # Pull a new container
+            docker image pull $(echo ${{ inputs.image_name }})
+            # Run a new container from a new image
+            if [ ${{ inputs.docker_port_mapping }} ]
+            then
+              docker run -d \
               --restart always \
-              $IMAGE
-
-            echo "Wait for container to boot"
-            sleep 10
-
-            if [ "$(docker inspect -f '{{.State.Running}}' $NEW_CONTAINER)" != "true" ]; then
-              echo "New container failed to start. Rolling back."
-              docker rm -f $NEW_CONTAINER
-              exit 1
+              --name $(echo ${{ inputs.docker_container_name }}) \
+              -p $(echo ${{ inputs.docker_port_mapping }}):8000 \
+              $(echo ${{ inputs.image_name }})
+            else 
+              docker run -d \
+              --restart always \
+              --name $(echo ${{ inputs.docker_container_name }}) \
+              $(echo ${{ inputs.image_name }})
             fi
 
-            echo "Stop old container"
-            docker rm -f $OLD_CONTAINER || true
+# name: digital-ocean-deploy
 
-            echo "Rename new container"
-            docker rename $NEW_CONTAINER $OLD_CONTAINER
+# on:
+#   workflow_call:
+#     inputs:
+#       image_name:
+#         required: true
+#         type: string
+#       docker_container_name:
+#         required: true
+#         type: string
+#       do_host:
+#         required: true
+#         type: string
+#       do_username:
+#         required: true
+#         type: string
+#       docker_port_mapping:
+#         required: false
+#         type: number
+#     secrets:
+#       do_ssh_key:
+#         required: true
 
-            echo "Cleanup old images"
-            docker image prune -f
+# jobs:
+#   digital-ocean-deploy:
+#     runs-on: ubuntu-latest
+#     timeout-minutes: 10
+
+#     steps:
+#       - name: Deploy via SSH
+#         uses: appleboy/ssh-action@v1.0.3
+#         with:
+#           host: ${{ inputs.do_host }}
+#           username: ${{ inputs.do_username }}
+#           key: ${{ secrets.do_ssh_key }}
+#           script: |
+#             IMAGE="${{ inputs.image_name }}"
+#             NEW_CONTAINER="${{ inputs.docker_container_name }}-new"
+#             OLD_CONTAINER="${{ inputs.docker_container_name }}"
+
+#             echo "Pull image"
+#             docker pull $IMAGE
+
+#             echo "Start new container"
+#             docker run -d \
+#               --name $NEW_CONTAINER \
+#               -p $(if [ "${{ inputs.docker_port_mapping }}" ]; then echo ${{ inputs.docker_port_mapping }}; else echo 8000; fi):8000 \
+#               --restart always \
+#               $IMAGE
+
+#             echo "Wait for container to boot"
+#             sleep 10
+
+#             if [ "$(docker inspect -f '{{.State.Running}}' $NEW_CONTAINER)" != "true" ]; then
+#               echo "New container failed to start. Rolling back."
+#               docker rm -f $NEW_CONTAINER
+#               exit 1
+#             fi
+
+#             echo "Stop old container"
+#             docker rm -f $OLD_CONTAINER || true
+
+#             echo "Rename new container"
+#             docker rename $NEW_CONTAINER $OLD_CONTAINER
+
+#             echo "Cleanup old images"
+#             docker image prune -f
